### ISSUE TITLE
Support for .net 4.6.1

### ISSUE THREAD

**Issue by joshgarwood** [openiddict/openiddict-samples#10]
Hi there!  I'm very eager to use this library as was using the built-in Microsoft auth solution with Identity, then realized I couldn't use the default SignInManager to get JWT's.  So, OpenIddict seems to be a perfect solution for me.  Unfortunately, I'm having trouble installing it.  Upon adding the necessary dependencies (OpenIddict and OAuth.Validation), I get an error when the packages are installed:

`Unable to resolve 'OpenIddict (>= 1.0.0)' for '.NETFramework,Version=v4.6.1'`

The "frameworks" node in my package.json looks like this:

` "frameworks": {
    "net461": {}
    }`

Is this supported, or will I not be able to use OpenIddict?

Thanks for your time!

**Comment by PinpointTownes** [comment]
Duplicate of https://github.com/openiddict/openiddict-core/issues/229 (for the record :sweat_smile:)

**Comment by joshgarwood** [comment]
@PinpointTownes  Yep!  Sorry about that!  I realized I made the "issue" in the wrong repo, so I closed it here and created it in the "core" repo.  Sorry for the clutter!
