### ISSUE TITLE
Replace the PowerShell run scripts by Project Tye

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-samples#100]
https://github.com/dotnet/tye

**Comment by kevinchalet** [comment]
@andregeuze interested in giving it a try? 😃

**Comment by andregeuze** [comment]
Actually, yes, I did try some things. But only on the Balosar sample so far. That seems to be the only project where you don't really need Tye for startup 😅

**Comment by kevinchalet** [comment]
FYI, I just update all the samples to target .NET 5.0, which shouldn't be a problem for this work item, but don't hesitate to ping me if you hit any issue.

**Comment by veikkoeeva** [comment]
I don't know if this helps, but maybe someone is interested: https://docs.steeltoe.io/articles/tech-tutorial-use-kubernetes-for-modern-net-apps-steeltoe-and-project-tye-are-your-path-to-productivity.html. Tye with Steeltoe for depyloments!

**Comment by kevinchalet** [comment]
Thanks for the pointer @veikkoeeva 👍🏻

**Comment by kevinchalet** [comment]
Project Tye doesn't seem to get any real love from Microsoft anymore, making adopting it a fairly unsafe bet at this point. Closjng for now.
