### ISSUE TITLE
Request for views to manage roles and claims

### ISSUE THREAD

**Issue by clooge** [openiddict/openiddict-samples#106]
Hello, we are using your samples for help in swapping out something else, not sure how that would pan out still evaluating. Can you please share some views for roles and claims management.

**Comment by kevinchalet** [comment]
Hi,

Roles and claims management is beyond the scope of OpenIddict, which is an OIDC stack. I'm not saying it wouldn't be useful to have such things, but I try to keep the samples as simple as possible, and focused on the OIDC exchange (not to mention that it's additional code I'd have to maintain, and I have very limited bandwidth).

Cheers.
