### ISSUE TITLE
Add Auth Server + Resource Server with Token Cross Validation Sample

### ISSUE THREAD

**Issue by JohnGalt1717** [openiddict/openiddict-samples#107]
Hi, from the samples I can't tell if the current V2 docs work for having an auth server and then a number of microservices that communicate with the auth server to validate tokens and what's involved.

It would be really great to have a sample that shows this scenario with a client that auths against the auth server, then requests data from a resource server which is validated across the wire to the auth server (or similar)

**Comment by kevinchalet** [comment]
Take a look at the Zirku sample:

> Zirku: implicit flow demo, with an Aurelia JS application acting as the client and two API projects using introspection (Api1) and local validation (Api2).
