### ISSUE TITLE
Velusia.Client Issue

### ISSUE THREAD

**Issue by cvipond** [openiddict/openiddict-samples#112]
I have the client running on:
https://localhost:44338/`

I have the authorisation Server running on:
https://localhost:44313/

I keep getting this error when clicking on the 'Sign In':

OpenIddict.Core.OpenIddictApplicationManager: Warning: Client validation failed because 'https://localhost:44338/signin-oidc' was not a valid redirect_uri for mvc.
OpenIddict.Server.OpenIddictServerDispatcher: Error: The authorization request was rejected because the redirect_uri was invalid: 'https://localhost:44338/signin-oidc'.
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'AuthorisationServer.Controllers.ErrorController.Error (AuthorisationServer)'
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "Error", controller = "Error"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Error() on controller AuthorisationServer.Controllers.ErrorController (AuthorisationServer).
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor: Information: Executing ViewResult, running view Error.
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor: Information: Executed ViewResult - view Error executed in 10.3159ms.
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action AuthorisationServer.Controllers.ErrorController.Error (AuthorisationServer) in 13.6734ms
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'AuthorisationServer.Controllers.ErrorController.Error (AuthorisationServer)'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 117.0766ms 400 text/html; charset=utf-8

**Comment by kevinchalet** [comment]
The samples were updated recently to use HTTPS endpoint. Update the client registration in the DB or remove it so it will be recreated by the sample app.

**Comment by cvipond** [comment]
thanks Kevin I'll give it a go
