### ISSUE TITLE
[enhancement] Updating Program.cs in Balosar to use appsettings.json config for Authority Url

### ISSUE THREAD

**Issue by qin-guan** [openiddict/openiddict-samples#113]

**Comment by qin-guan** [comment]
Sorry for the lack of description, I meant doing something similar to [this](https://github.com/dotnet/aspnetcore/pull/20790/files/43e15fdca35f9610eecfe8e248b6a93b75a4df03#diff-c4e7240e902948107e2d9f9743aa0baa35478e9378b1dafadcc3b64ae687d1d4), where `options.ProviderOptions.Authority` is set by `appsettings.json`

**Comment by kevinchalet** [comment]
Having strongly-typed options and using `IConfiguration` is something I encourage and do myself a lot but I don't think it has enough added value to justify spending time updating all the sample apps.
