### ISSUE TITLE
Example for API Gateway with JWT

### ISSUE THREAD

**Issue by boukenka** [openiddict/openiddict-samples#116]
Hello,

Thank you first for this project. 😃 

I tried to use the examples.
So far, I have not found an answer to my requirement (or maybe I haven't looked hard enough).
I am looking for the following flow :

1. A console sends its identifiers to a gateway API.
2. The Gateway API returns a JWT and the URL of the API resource that the console can access.
The JWT contains a role. This role gives the right to use the URL in the API resource controller..
3. The console connects to the API resource with the JWT it received and the URL.

A) Is this possible with openiddict? If so, is there an example I could follow?
B) Is it also possible to define the issuer, the expiration datetime/period of validity and the audience in the JWT generated by openiddict?
C) And how do you replace the following code when this is a production environment ?

``options.AddDevelopmentEncryptionCertificate().AddDevelopmentSigningCertificate();``

Thank you (and sorry for all my questions)

PS : If the URL cannot be provided by the gateway API, it is still OK. 😃 
PS : I do not wish to use Orchard ! 
PS: The flow should give the possibility to connect to different API resources.
I mean that the identifiers of the console give the possibility to access the API A resource (for example) but not the API B resource. Another set of console identifiers gives the possibility to access the API B resource (for example) but not the API A resource. Is it via scope ?

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, GitHub issues are reserved to sponsors as a way to thank them for helping the project. Please consider sponsoring it or post your question on StackOverflow.

Thanks.
