### ISSUE TITLE
Zirku example: Logging out with the client gives an HTTP 500 error

### ISSUE THREAD

**Issue by Devwulf** [openiddict/openiddict-samples#117]
The error on the server-side that it gives specifically is:

`System.InvalidOperationException: The logout request was not handled.`

It seems adding this line in Startup.cs of the server, when enabling endpoint passthroughs, fixes the issue:
```
options.UseAspNetCore()
    ...
    .EnableLogoutEndpointPassthrough()
    ...;
```

Quick question, is it better to logout using the /Account/LogOff endpoint or the /connect/logout endpoint?

**Comment by kevinchalet** [comment]
Thanks. Fixed as part of https://github.com/openiddict/openiddict-samples/commit/9feb9db53ad588ae0042e4c61a1b3a17b5af2314.

**Comment by kevinchalet** [comment]
> Quick question, is it better to logout using the /Account/LogOff endpoint or the /connect/logout endpoint?

If you want to redirect your users back to the client, a logout endpoint managed by OpenIddict is what you need.
