### ISSUE TITLE
Issue: "Velusia" sample code does not work

### ISSUE THREAD

**Issue by RobertChanphakeo** [openiddict/openiddict-samples#122]
Sample code for "Velusia" client/server project is not working as expected.

### To reproduce
1. Download sample code
2. Run both Velusia Server and Velusia Client
3. Client on "Sign in" button via Velusia client web app

### Error
invalid_request The specified 'redirect_uri' is not valid for this client application.

"warn: OpenIddict.Core.OpenIddictApplicationManager[0]
      Client validation failed because 'https://localhost:44338/signin-oidc' was not a valid redirect_uri for mvc.
fail: OpenIddict.Server.OpenIddictServerDispatcher[0]
      The authorization request was rejected because the redirect_uri was invalid: 'https://localhost:44338/signin-oidc'."

note: After verifying the server project, it was found that https://localhost:44338/signin-oidc is actually a valid redirect uri

**Comment by kevinchalet** [comment]
`OpenIddict.Server.OpenIddictServerDispatcher` doesn't exist in OpenIddict 3.0, so I suspect you're simply using an obsolete clone or are not taking a look at the right branch (dev).

**Comment by RobertChanphakeo** [comment]
The sample code if from "dev" branch, and I just verified the project uses .NET 5 and its running OpenIddict 3.0.0

I redownloaded the sample code from the "dev" branch, i'm getting the same error message as described above.

**Comment by kevinchalet** [comment]
Is there a chance you're running the sample with a database created a while ago, when the redirect_uris were not HTTPS address? Try to delete and recreate the DB.

**Comment by RobertChanphakeo** [comment]
I just checked the database records and it was using http rather than https, (this might have been from a previous version), a quick database update resolved the issue! 👍

**Comment by kevinchalet** [comment]
Great to hear!

**Comment by TomTomDam** [comment]
Hi, I am currently having this same problem trying to replicate this project in NET 5.0. The only difference is my project is not using Quartz.

As you guys discussed before, I have checked the redirect_uri value in my database and my OpenIddictApplications.RedirectUris value is:
`["https://localhost:44338/signin-oidc"]`

When I run click "Sign in", after returning a challenge from /login, it doesn't even hit the /connect/authorize endpoint and gives me the same error:
`The specified 'redirect_uri' is not valid for this client application.`

Any ideas? Maybe the exclusion of Quartz has broken something in my project? Thank you.

**Comment by kmcgahey1** [comment]
I recently ran into this error too and found it occurred because I had copied my database from one environment to another.  After I cleared the OpenIddict data and restarted the app, it worked:
  delete from [dbo].[OpenIddictTokens];
  delete from [dbo].[OpenIddictAuthorizations];
  delete from [dbo].[OpenIddictApplications];
