### ISSUE TITLE
Add Docker Support Sample

### ISSUE THREAD

**Issue by dabasejumper** [openiddict/openiddict-samples#123]
### Is your feature request related to a problem?
I'm trying to get a .NET Core 5 solution that has three containers.

1. Openiddict Identity Server - utilizing EF Identity
2. Web API Service - Using JWT tokens from Client
3. MVC Razor Client 

### Describe the solution you'd like
I'd love to see what a dockerized solution would look like for a team to all distribute the same way.

**Comment by kevinchalet** [comment]
Technically, adding Docker support to an ASP.NET Core application (using OpenIddict or not) doesn't fundamentally change the way it works, so having Docker-based samples wouldn't help you much for the OAuth 2.0/OIDC part.

That said, we have another ticket that tracks adding Project Tye support, which should make the deployment story easier: https://github.com/openiddict/openiddict-samples/issues/100.

**Comment by kevinchalet** [comment]
Looks like the interest is fairly low. Let's close it for now.
