### ISSUE TITLE
Balosar (blazor) sample

### ISSUE THREAD

**Issue by supervas** [openiddict/openiddict-samples#128]
Once the example has been executed, when trying to access the "Login" through the link at the top, the following message appears:

> There was an error trying to log you in: 'Invalid response Content-Type: text/html, from URL: https://localhost:44310/.well-known/openid-configuration'

However, if we first access "Register" and, from there, click on "Login", then the login screen does appear.

Is it necessary any additional configuration in the execution so that it does not return this error?

**Comment by kevinchalet** [comment]
I can't reproduce this issue locally. If you're still experiencing it, please provide logs and a network trace.

**Comment by MortInfinite** [comment]
I experienced the exact same error, using the Balosar sample. After debugging for 6 hours, I finally found out that clearing my browser cache would make the problem go away.
