### ISSUE TITLE
Velusia Client does not work

### ISSUE THREAD

**Issue by HamedFathi** [openiddict/openiddict-samples#131]
### Describe the bug

I tried to run the `Velusia` sample but I got an error.

![server](https://user-images.githubusercontent.com/8418700/114002379-0efbaa80-9872-11eb-9c88-1334dc13905e.png)

Seems the server is OK 

![client 1](https://user-images.githubusercontent.com/8418700/114002466-22a71100-9872-11eb-90db-ee318ea37ce7.png)

And the client project runs without problem, but after clicking on `Sign in` I got these

![client 2](https://user-images.githubusercontent.com/8418700/114002592-3eaab280-9872-11eb-84f5-f6aeaa06036a.png)

After reloading the page

![client 3](https://user-images.githubusercontent.com/8418700/114002627-48341a80-9872-11eb-9fd7-d4be9a37182e.png)

### Further technical details

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
```

Can anyone guide me on how to fix this?

**Comment by kevinchalet** [comment]
Should be fixed by https://github.com/openiddict/openiddict-samples/commit/0bf7ecc82524dcd4a5c34b5cc4c77b9545935b3b.
