### ISSUE TITLE
Sometimes getting 401 when validating tokens on Velusia sample

### ISSUE THREAD

**Issue by cvipond** [openiddict/openiddict-samples#141]
### Describe the bug
When using this sample, if the token expires you get a 401 error rather than refreshing the token or a login page. 

### Further technical details
 ASP.NET 5.

**Comment by kevinchalet** [comment]
Fixed: https://github.com/openiddict/openiddict-samples/commit/e61ca196cd79d7d7571e2c12140f8d3184b07ca4.
