### ISSUE TITLE
Bare bones example without database, quartz, and using bare minimum options would be nice

### ISSUE THREAD

**Issue by az-oolloow** [openiddict/openiddict-samples#142]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.
Example: I am trying to do understand what is the minimum code i need from OpenIdDict to respond to OpenId Connect clients, and I find examples and documentation overloaded with code setting up EF core, sample data, and remapping id columns; quartz jobs to prune tokens from db (according to the comment)

### Describe the solution you'd like
A simple, bare bones code that does not have any UI and simply responds to any incoming request as if the user was authorised to the world of clients, showing HOW to add user provider, client app provider, signing keys etc.

**Comment by kevinchalet** [comment]
See https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/

That said, as mentioned in the post, using the degraded mode as serious implications so don't use it lightly (OpenIddict works best with EF or MongoDB).
