### ISSUE TITLE
Update or add sample to show RefreshTokenFlow 

### ISSUE THREAD

**Issue by Toxicable** [openiddict/openiddict-samples#15]
Currently no sampels show how to use the RefreshTokenFlow

**Comment by PinpointTownes** [comment]
Good idea :+1: 

It should be easy to add that in the password flow sample.

**Comment by PinpointTownes** [comment]
For the record, the refresh token flow sample can be found here: https://github.com/openiddict/openiddict-samples/tree/master/samples/RefreshFlow
