### ISSUE TITLE
I wonder what the table OpeniddictAuthorization do?

### ISSUE THREAD

**Issue by dinhan92** [openiddict/openiddict-samples#158]
I see the table OpeniddictAuthorization appear in the database, but there is no data in it. I wonder what role it has in the flow ? And How to add data to it? I am using Zirku.

Please help!!! Thank you very much!!!!

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, GitHub issues are reserved to sponsors as a way to thank them for helping the project. Please consider sponsoring it or post your question on StackOverflow.

Thanks.
