### ISSUE TITLE
How can I add custom claims ?

### ISSUE THREAD

**Issue by AbdoDabbas** [openiddict/openiddict-samples#16]
I'm trying to follow this sample:
[https://github.com/openiddict/openiddict-samples/tree/master/samples/PasswordFlow](url)
But how to add custom claims to the returned response ?
Not only serialize them in the token, I want them to be returned clearly in the response of the token request.

**Comment by PinpointTownes** [comment]
You can read https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/ for an example of how to do that (in the `Implementing the Connect/Token Endpoint` section)

**Comment by AbdoDabbas** [comment]
Thanks for replying, I'll read it.
Another question please, what's the difference between what you implemented in this sample, and the OpenIddict server library which contains Authentication provider ?

**Comment by PinpointTownes** [comment]
As mentioned in the README, OpenIddict is based on ASOS. It implements all the validation routines for you and adds a bunch of security constraints so you only have to care about validating the user password and returning an identity. Everything else is managed for you by OpenIddict.
