### ISSUE TITLE
Assertion Grant Example

### ISSUE THREAD

**Issue by cliedeman** [openiddict/openiddict-samples#173]
### Is your feature request related to a problem?
Create an Example of `assertion grant`.
I managed to piece together a working example using these references:
- https://stackoverflow.com/questions/40257981/exchanging-a-google-idtoken-for-local-openid-token-c-sharp
- https://stackoverflow.com/questions/39008642/use-openidconnectserver-and-try-to-connect-to-facebook-through-api-service/39018048#39018048

and a fair bit of googling. The stackoverflow answers code samples also don't compile with the latest openiddict. I am willing to contribute this

### Describe the solution you'd like
A new example showing assertion grant with google or add it to an existing example

### Additional context
I plan to omit the identity token signature validation from the example because you need quite a bit of plumbing to add it. Some more context here - https://github.com/dotnet/aspnetcore/issues/24309

**Comment by kevinchalet** [comment]
Hey,

Technically, the assertion grant is implemented almost exactly like the password flow in OpenIddict. If we leave the assertion validation part as an exercise, I'm not sure it will be worth having a dedicated sample in this case. Instead, you may want to update the Zirku sample (that currently uses the code flow but can be tweaked to use the assertion flow).

Happy new year!
