### ISSUE TITLE
Repair the aurelia part of the implicit flow demo.

### ISSUE THREAD

**Issue by shaunluttin** [openiddict/openiddict-samples#18]
With commit `e1aeb5c5a3bd939f4cfa1a639e2110b78715074f` and node 6.9.1, the call to `npm run start` produces dozens of TypeScript errors. 

> Cannot find name... 

@PinpointTownes Please assign this issue to me and I will fix it with a PR.

**Comment by PinpointTownes** [comment]
Done: https://github.com/openiddict/openiddict-samples/commit/828bd9e27b60e50bb0eff3291dd7bbd56e5b62e8 :+1:
