### ISSUE TITLE
Any samples for grant type client credentials and client assertions?

### ISSUE THREAD

**Issue by svasui123** [openiddict/openiddict-samples#193]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

We are testing a Smart FHIR implementation with openiddict. I am stuck on the client assertion flow and would request any links to documentation or samples that implement or can help implement client assertion and client credentials.

**Comment by svasui123** [comment]
It would definitely be of great value to anyone who is using Openiddict to comply with FHIR and OAUTH2 requirements. Assertion grant flows are 1 of the 4 vignettes that are tested. I will look at the samples and define a custom flow that handles assertion grants (I saw your comment about this flow technically being similar to the password flow). We are currently going through the certification process and this is the last hurdle. 

Yes adding it to 4.0 would help.

**Comment by kevinchalet** [comment]
> Assertion grant flows are 1 of the 4 vignettes that are tested. I will look at the samples and define a custom flow that handles assertion grants (I saw your comment about this flow technically being similar to the password flow).

It's worth noting that client assertions != assertion grants: the former are generated to serve as client credentials while the second are generated to serve as an entity identity (typically a user).

**Comment by kevinchalet** [comment]
If you can't/don't want to wait for built-in support, you'll need to replace these 2 handlers:
  - https://github.com/openiddict/openiddict-core/blob/eb8715d96440c05400b3613d37ca64385d79c042/src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs#L498-L537: `ValidateClientCredentialsParameters` blocks the request if `client_id` and/or `client_secret` is/are missing. You'll want to replace it by an equivalent handler that supports the `client_assertion`/`client_assertion_type` parameters.

  - https://github.com/openiddict/openiddict-core/blob/eb8715d96440c05400b3613d37ca64385d79c042/src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs#L928-L986: `ValidateClientSecret` only works with a `client_secret` so you'll need a custom handler that uses `client_assertion`/`client_assertion_type`.

It's not mandatory but you'll probably want to tweak the configuration document to indicate your server instance supports client assertions. For that, you'll need to add `private_key_jwt` (assuming you're using asymmetric signing keys) to `HandleConfigurationRequestContext.TokenEndpointAuthenticationMethods`.

See https://github.com/openiddict/openiddict-core/blob/eb8715d96440c05400b3613d37ca64385d79c042/src/OpenIddict.Server/OpenIddictServerHandlers.Discovery.cs#L491-L535 for the handler responsible for adding `client_secret_basic`/`client_secret_post`.

**Comment by svasui123** [comment]
I followed the instructions given in https://github.com/openiddict/openiddict-core/issues/736 to wire up an event handler. When I try to add options.AddEventHandler<HandleConfigurationRequestContext, MyEventHandler> (); under AddServer it is giving me an error. What is the new syntax?

**Comment by kevinchalet** [comment]
> Having said that I think working with these handlers would help me better understand this extremely well done package.

Haha, thanks for the kind words! 😃 

> What is the new syntax?

I'd recommend using the same approach as the one used for the built-in handlers:

```csharp
public class YourCustomHandler : IOpenIddictServerHandler<...>
{
    /// <summary>
    /// Gets the default descriptor definition assigned to this handler.
    /// </summary>
    public static OpenIddictServerHandlerDescriptor Descriptor { get; }
        = OpenIddictServerHandlerDescriptor.CreateBuilder<...>()
            .UseSingletonHandler<YourCustomHandler>()
            .SetOrder(...)
            .SetType(OpenIddictServerHandlerType.Custom)
            .Build();

    /// <inheritdoc/>
    public ValueTask HandleAsync(... context)
    {
        ...
    }
}
```

```csharp
options.AddEventHandler(YourCustomHandler.Descriptor);
```

Alternatively, you can also use inline handlers, as shown in https://documentation.openiddict.com/guides/index.html#events-model.

**Comment by svasui123** [comment]
Hi,

 

I am able to override the handlers for ValidateClientCredentialsParameters and the AttachClientAuthenticationMethods. When I try to override the ValidAteCLientSecret I get run time error:

System.InvalidOperationException: 'The core services must be registered when enabling the OpenIddict server feature. To register the OpenIddict core services, reference the 'OpenIddict.Core' package and call 'services.AddOpenIddict().AddCore()' from 'ConfigureServices'.

 

My Program.cs

builder.Services.AddOpenIddict()

 

    // Register the OpenIddict core components.

    .AddCore(options =>

    {

        // Check if next line fixes the error.

        options.SetDefaultApplicationEntity<OpenIddictEntityFrameworkCoreApplication>();

        // Configure OpenIddict to use the Entity Framework Core stores and models.

        // Note: call ReplaceDefaultEntities() to replace the default OpenIddict entities.

       options.UseEntityFrameworkCore()

               .UseDbContext<ApplicationDbContext>()

               ;

   

 

        // Enable Quartz.NET integration.

        //options.UseQuartz();

    })

 

    // Register the OpenIddict server components.

    .AddServer(options =>

    {

        // Enable the authorization, logout, token and userinfo endpoints.

        options.AllowClientCredentialsFlow();

        options.SetTokenEndpointUris(builder.Configuration["OpenIddict:Endpoints:Token"]);

 

        Console.WriteLine("Config:" + builder.Configuration["OpenIddict:Endpoints:Token"]);

 

        // to enable revoke tokens

        // Encryption and signing of tokens

        options

        .AddEphemeralEncryptionKey()

        .AddEphemeralSigningKey()

        .DisableAccessTokenEncryption()

        ;

 

        // Mark the "email", "profile" and "roles" scopes as supported scopes.

        options.RegisterScopes(Scopes.Email, Scopes.Profile, Scopes.Roles, Scopes.OfflineAccess, Scopes.OpenId, "scp:fhirUser", "scp:patient/Patient.read");

        //options.RegisterClaims(Claims.Subject, Claims.Name, Claims.Username, "fhirUser");

 

        // Register the signing and encryption credentials.

       options.AddDevelopmentEncryptionCertificate()

        .AddDevelopmentSigningCertificate();

 

        // Register the ASP.NET Core host and configure the ASP.NET Core-specific options.

        options.UseAspNetCore()

        .EnableTokenEndpointPassthrough()

        ;

        options.AddEventHandler(MyValidateClientCredentialsParameters.Descriptor);

        options.AddEventHandler(MyValidateClientSecret.Descriptor);

        options.AddEventHandler(MyAttachClientAuthenticationMethods.Descriptor);

 

    })    // Register the OpenIddict validation components.

    .AddValidation(options =>

    {

        options.UseLocalServer();

        // Register the ASP.NET Core host.

        options.UseAspNetCore();

        //to cater to immediate access token revocation

        options.EnableTokenEntryValidation();

    });

 

Code where it crashes:

       public class MyValidateClientSecret : ValidateClientSecret, IOpenIddictServerHandler<ValidateTokenRequestContext>

        {

            private readonly IOpenIddictApplicationManager _applicationManager;

 

            public MyValidateClientSecret() => throw new InvalidOperationException(OpenIddictResources.GetResourceString(OpenIddictResources.ID0016));

 

            public MyValidateClientSecret(IOpenIddictApplicationManager applicationManager)

                => _applicationManager = applicationManager ?? throw new ArgumentNullException(nameof(applicationManager));

Crashes on the above line

            /// <summary>

            /// Gets the default descriptor definition assigned to this handler.

            /// Turn off RequireCLientId

            /// </summary>

            public static new OpenIddictServerHandlerDescriptor Descriptor { get; }

                = OpenIddictServerHandlerDescriptor.CreateBuilder<ValidateTokenRequestContext>()

                    //.AddFilter<RequireClientIdParameter>()

                    .AddFilter<RequireDegradedModeDisabled>()

                    .UseScopedHandler<MyValidateClientSecret>()

                    .SetOrder(OpenIddictServerHandlers.Authentication.ValidateClientType.Descriptor.Order + 1_000)

                    .SetType(OpenIddictServerHandlerType.Custom)

                    .Build();

 

What am I missing?

 

Best Regards

Vasu

**Comment by kevinchalet** [comment]
I suspect this could be related to the fact you're trying to subclass the built-in `ValidateClientSecret` handler, which is something you should never do.

Instead, create your own independent handler - that don't subclass `ValidateClientSecret` - and remove the built-in one by doing `options.RemoveEventHandler(ValidateClientSecret.Descriptor)`.

**Comment by svasui123** [comment]
Hi Kevin,

 

This is what I ended up doing. I am currently working on adding an additional table to verify the jwksurl and store the public keys (if jwks url is not given then it will default to the stored key .. this is not recommended but is a requirement). Also messages are hard coded since we first wanted to get a working model and the documentation URI are incorrect.

 

Best Regards

Vasu

 

From: ***@***.*** ***@***.***> 
Sent: Sunday, June 5, 2022 6:09 PM
To: 'openiddict/openiddict-samples' ***@***.***>; 'openiddict/openiddict-samples' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [openiddict/openiddict-samples] Any samples for grant type client credentials and client assertions? (Issue #193)

 

Thank you for your prompt response.

 

I was actually overriding the method by subclassing and using new to override.

 

I removed the subclassing and removed the built-in handlers. I am now able to see the flow into the custom handlers after overriding ValidateClientIdParameter to allow requests with grant type client credentials and  clientassertion and clientassertiontype in the request.

 

I will keep you posted on the progress and share the code after implementing the client-assertion requirements.

**Comment by svasui123** [comment]
Hi Kevin,

 

Is there a new version with the private_key_jwt included?

 

Best Regards

Vasu

**Comment by kevinchalet** [comment]
Hey Vasu,

Support for client authentication assertions in the server stack is tracked by https://github.com/openiddict/openiddict-core/issues/1251. 4.0 (whose 3rd preview shipped yesterday) will mostly focus on the whole new client stack so it's likely something that will need to wait a bit (maybe 5.0 or 6.0?).

Cheers.

**Comment by kevinchalet** [comment]
For the record, client assertions support is part of the 5.0 preview1 release that shipped today: https://kevinchalet.com/2023/10/20/introducing-native-applications-per-client-token-lifetimes-and-client-assertions-support-in-openiddict-5-0-preview1/

**Comment by svasui123** [comment]
Thank you. We will check this.
