### ISSUE TITLE
Hook into introspection endpoint

### ISSUE THREAD

**Issue by xperiandri** [openiddict/openiddict-samples#195]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x

### Question

Is there a sample that demonstrates how to hook into introspection endpoint?
I suppose to execute some additional logic there

**Comment by kevinchalet** [comment]
> Is there a sample that demonstrates how to hook into introspection endpoint?

Nope, as it's likely an advanced scenario. You can, however, use the events model to add any logic you want to the introspection request processing pipeline.
