### ISSUE TITLE
Error with Balosar Client

### ISSUE THREAD

**Issue by dlandi** [openiddict/openiddict-samples#229]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Describe the bug

Hi. Just running the Balosar client and Server I get and error trying to login or register from the client:

![image](https://user-images.githubusercontent.com/3196088/218493403-fb339fd0-a1ea-4bdf-89c4-b020ac915c59.png)

### To reproduce

see image

**Comment by kevinchalet** [comment]
Hey,

I just tested on my machine and it worked fine. The URL on your screenshot seems wrong ; how did you start the app?
Could you please try with `https://localhost:44310/`?

Cheers.

**Comment by dlandi** [comment]
Ok. I made sure I had a clean branch and then I need to delete the databases *and* then I need to clear the chrome cache before it started working. 

I'll start a new thread.

**Comment by luojianxhlxt** [comment]
The Balosar client default listening on  https://localhost:5001 and  http://localhost:5000 . 
And while login to server , this will report 
` Access to XMLHttpRequest at 'https://localhost:44310/.well-known/openid-configuration' from origin 'https://localhost:5001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by kevinchalet** [comment]
The Balosar client is expected to be served by the server app: in that case, the port is the same between the server host and its WASM companion and CORS isn't required.
