### ISSUE TITLE
Add sdk to global.json to indicate which CLI the samples support.

### ISSUE THREAD

**Issue by shaunluttin** [openiddict/openiddict-samples#24]
Right now, the global.json says this: 
```
{
    "projects": [ "samples" ]
}
```
Update it to say this, or to say something equivalent, to specify which SDK the samples support:
```
{
    "projects": [ "samples" ], 
    "sdk": { "version": "1.0.0-preview2-003133" }
}
```
That way, those who have multiple CLI versions installed can run the samples more easily.

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/openiddict/openiddict-samples/commit/078f5594c25b238c3c2be8cd934ffdc22f1882a7.
