### ISSUE TITLE
authorize is redirected to /Account/Login

### ISSUE THREAD

**Issue by haison8x** [openiddict/openiddict-samples#25]
I clone the samples and upgrade all nuget packages. However, the code flow doesn't work
The authorization request always is redirected to http://localhost:54540/Account/Login?ReturnUrl
Please see the authorization request and attached image for more information
Authorization request: 
http://localhost:54540/connect/authorize?client_id=myClient&redirect_uri=http%3A%2F%2Flocalhost%3A53507%2Fsignin-oidc&response_type=code&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=636167893996349017.NWU4YzVjMDItZmFjOS00ZmEzLTgyMDMtZDlhMTI5OWUxZjlhZWQ1ZGY1MmYtZTQ5NS00N2UxLTgwYzctODc5MWExMzY0MWZk&state=CfDJ8M8rXcIuRFFIqll6CucWCEqm9UaHF0HB3uNC0WbbbZldGtjlDyF9fRMmLcg1FlSPPSDDTRsCLoRfD0wTu3lCNyVzsrsxsn3oHof0rl9dCatAR7RoqvgWuSfq1GG3vL1hE0LkDlg7bp7bxAKETLdVBkEsw_ltKiqwFWRUPghlSXaPSbVgiIuTuOhwiZTvyXHSOWV5tQdgq5mFnMHkhr0hkiGuzXt5k1oF_fZ8ZTUJRd6QLA6Et1TQxYvOy8XqBwO5_VpSSGGVID3wIDk3Anzd7IXvCO2xVhiqqWwpuOjtifrK

![openiddict](https://cloud.githubusercontent.com/assets/3090475/21006436/828df304-bd6b-11e6-9faf-7ffd7f8b3272.png)

**Comment by PinpointTownes** [comment]
Are you using the 1.1.0 bits? If so, you're impacted by a design change in ASP.NET Core. Read https://github.com/aspnet/Security/issues/1044 for more information.

**Comment by haison8x** [comment]
Hi PinpointTownes!
