### ISSUE TITLE
An unhandled exception occurred while processing the request. at page signin-oidc

### ISSUE THREAD

**Issue by haison8x** [openiddict/openiddict-samples#26]
I add UseOAuthIntrospection but I stuck at the page signin-oidc
![openiddict1](https://cloud.githubusercontent.com/assets/3090475/21087016/602c1a66-c054-11e6-89f0-75161a25ea65.png)
![openiddict2](https://cloud.githubusercontent.com/assets/3090475/21087020/64fba552-c054-11e6-82af-0e82ac8175be.png)

What should I do? Please help

**Comment by PinpointTownes** [comment]
Not sure how it's related to introspection... the stack trace indicates the error is caused by a 500 response returned by your userinfo endpoint.
