### ISSUE TITLE
Understand how to use symmetric key for token validation

### ISSUE THREAD

**Issue by dgxhubbard** [openiddict/openiddict-samples#260]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

I want to use a symmetric key with openiddict server and clients. I see that Zirku Server and Api2 use a symmetric key. And that's all I understand. I do not see how to run Client2 (if thats what I need to do) and Server and Api2. Is there some explanation on how to run this and to show the token being verified, because right now I am lost.

Any help you can provide would be very useful

**Comment by kevinchalet** [comment]
> I do not see how to run Client2 (if thats what I need to do) and Server and Api2.

You don't have to run Client2: it's just a JS demo for those who want to see a minimal JS sample. If you prefer trying a .NET client, run Client1 instead.

Regarding Api2, it's a regular .NET app, just select Api1, Api2, Client1 and Server as the startup projects in VS or call `dotnet run` in each folder to ensure all these apps are started.

Let me know if you need additional guidance.

**Comment by kevinchalet** [comment]
Closing. Additional questions are tracked by https://github.com/openiddict/openiddict-samples/issues/261.
