### ISSUE TITLE
Add a Blazor Hybrid sample

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-samples#281]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

... using either WPF or WinForms as the main app.

**Comment by Eddie-Hartman** [comment]
@kevinchalet just FYI the MAUI link in the README is broken (404). See MAUI sample link here: https://github.com/openiddict/openiddict-samples?tab=readme-ov-file#external-samples

Is this supposed to be the new sample? https://github.com/openiddict/openiddict-core/tree/dev/sandbox/OpenIddict.Sandbox.Maui.Client
I'm specifically looking for Blazor Hybrid (MAUI).

**Comment by kevinchalet** [comment]
> @kevinchalet just FYI the MAUI link in the README is broken (404). See MAUI sample link here: https://github.com/openiddict/openiddict-samples?tab=readme-ov-file#external-samples

Ah yeah, nice catch. I'll fix that.

> Is this supposed to be the new sample? https://github.com/openiddict/openiddict-core/tree/dev/sandbox/OpenIddict.Sandbox.Maui.Client
I'm specifically looking for Blazor Hybrid (MAUI).

Yeah.

Note: there's no dedicated "Blazor Hybrid on MAUI" sample specifically but in that model, Blazor is not where the magic happens anyway (as you can see with this Blazor Hybrid on WPF, there's nothing Blazor-specific in how interactive challenges are started or handled: https://github.com/openiddict/openiddict-samples/blob/dev/samples/Sorgan/Sorgan.BlazorHybrid.Client/Login.razor).
