### ISSUE TITLE
.NET8 Blazor Webapp samples

### ISSUE THREAD

**Issue by odyyudah** [openiddict/openiddict-samples#289]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Describe the solution you'd like

Currently we have old Blazor template (Hosted WASM) in the samples.
Request to have .NET 8 Blazor WebApp (InteractiveServer, InteractiveWebassembly, Interactive Auto, Static SSR) samples working with OIDC.
Thank you

**Comment by kevinchalet** [comment]
Hi,

Looks like GitHub didn't recognize you as a sponsor. Did you sponsor the project with a different account/enterprise account?
