### ISSUE TITLE
Client logout without logging completely out of the IDP

### ISSUE THREAD

**Issue by kdudley21** [openiddict/openiddict-samples#291]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.1.0

### Question

Is there a way to log a user out of a specific application/client without logging them completely out of the IDP ?

**Comment by kevinchalet** [comment]
> Is there a way to log a user out of a specific application/client without logging them completely out of the IDP ?

Nope, [backchannel logout](https://openid.net/specs/openid-connect-backchannel-1_0.html) is not currently supported (and frontchannel logout is a dead feature due to the ban of third-party cookies in recent browsers).

What's your scenario?

**Comment by kdudley21** [comment]
Thanks ! 

This isnt currently required but lets say a user is authenticated in application A and application B. The user logs out of application A but wants to stay logged into application B. 

The more I think about it the user would still be logged into application B by default since it has already performed the authentication process. So I think I'm good and I am just overthinking scenarios.

**Comment by kevinchalet** [comment]
> The more I think about it the user would still be logged into application B by default since it has already performed the authentication process.

Ah yeah, most clients keep a local session that is independent from the IdP session (typically, by simply using an authentication cookie): clearing your session from client B doesn't affect client A.

**Comment by kdudley21** [comment]
Yep! Thanks again for all your help!

**Comment by Grizzlly** [comment]
@kevinchalet Will backchannel logout ever be supported? Thank you in advance.

**Comment by kevinchalet** [comment]
@Grizzlly if there's a strong demand, maybe. But it's a very limited solution as it only works with server-side web apps and can't be directly used by SPAs, desktop and mobile clients, so it's not very appealing.
