### ISSUE TITLE
Refresh token not being issued

### ISSUE THREAD

**Issue by JoniDS** [openiddict/openiddict-samples#3]
Hi, 

I tried the sample (MVC server), and when a make a post request to "../connect/token" I get issued a token, but never a refresh token. Am I missing something?

Thank you

**Comment by devilsuraj** [comment]
how do you make the request?? and what you get in response post everything

**Comment by JoniDS** [comment]
![capture](https://cloud.githubusercontent.com/assets/1437129/16997463/7f4c88b8-4ead-11e6-8182-830b5549a7fa.JPG)

**Comment by PinpointTownes** [comment]
The answer is given in the last section of this post: http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-adding-custom-claims-and-granting-scopes/ :smile:

**Comment by JoniDS** [comment]
My bad, thank you for the prompt reply.
