### ISSUE TITLE
auth-ready vs logged-in reduers?

### ISSUE THREAD

**Issue by asadsahi** [openiddict/openiddict-samples#30]
@PinpointTownes @Toxicable

In Refresh flow sample I am confused regarding these two reducers, why we use one over the other.

![image](https://cloud.githubusercontent.com/assets/3470892/22002493/5b10caf2-dc44-11e6-892b-cef921d9d300.png)

**Comment by Toxicable** [comment]
`auth-ready` tells the Application when the the startup processes have completed and it's ready to give the tokens.
`logged-in` can be used by the UI to show if a user is logged-in or not.
So if on startup you want to see if the a user is logged in you should first check to see if the auth is ready, then access the logged-in state.
I understand that this is kind of confusing and did have initial hesitations when writing it, i'm working on a another project which does very similar things but tidies it up for you so you wouldn't have to worry about this `auth-ready` variable outside of the Auth class, once i've put this other method through it's paces in my own use cases i'll put it up for PR here.

**Comment by asadsahi** [comment]
@Toxicable looking forward to your change. Thanks. So in theory I don't have to use token ready state as in every situation logged in state suffice the purpose.

**Comment by Toxicable** [comment]
Currently you should only need to check `auth-ready` if the accessor is being run near the start up of the app, once start up is done then it will always be set to true so `logged-in` will suffice

**Comment by PinpointTownes** [comment]
@Toxicable thanks the great explanation :+1:
