### ISSUE TITLE
HttpC

### ISSUE THREAD

**Issue by DinoHad** [openiddict/openiddict-samples#308]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.3.0

### To reproduce

```

**Comment by kevinchalet** [comment]
Hi,

Support is reserved to sponsors and contributors. For more information on how to sponsor the project on GitHub, visit https://github.com/sponsors/kevinchalet.

Hope to see you on board soon!
