### ISSUE TITLE
External Authentication with Google does not work with the new Google Login button

### ISSUE THREAD

**Issue by jacob925** [openiddict/openiddict-samples#328]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.0

### Describe the bug

Hello, I am using the Velusia server to test. 
When adding google auth using:

the resulting button works great! (uses OAuth, I believe)

However, if I follow the google directions here: https://developers.google.com/identity/gsi/web/guides/display-button#html_1
and add the html code: 

then the resulting button does authenticate with google but on callback produces an error: (below)

I am sure it's something I am doing wrong but all I have done is added the new button and implemented google auth.

If you reach out to me directly I will share my client id / secret and you can reproduce the issue.

Thanks,
Jacob Clark
support@jspending.com

### To reproduce

add google auth provider to Velusia.Server startup.cs
options.UseWebProviders()
    .AddGoogle(options =>
    {
        options.SetClientId("[Redacted].apps.googleusercontent.com")
               .SetClientSecret("[REDACTED]")
               .SetRedirectUri("callback/login/google");
    });

Add the google button code. I added it directly to the home page for simplicity
<script src="https://accounts.google.com/gsi/client" async></script>
    <div id="g_id_onload"
        data-client_id="YOUR_GOOGLE_CLIENT_ID"
        data-login_uri="https://your.domain/your_login_endpoint"
        data-auto_prompt="false">
    </div>
    <div class="g_id_signin"
        data-type="standard"
        data-size="large"
        data-theme="outline"
        data-text="sign_in_with"
        data-shape="rectangular"
        data-logo_alignment="left">
    </div>
    

### Exceptions (if any)

```shell
error:missing_token
error_description:The security token is missing.
error_uri:https://documentation.openiddict.com/errors/ID2000
```

**Comment by kevinchalet** [comment]
Hey @jacob925,

Thanks for sponsoring the project! ❤️ 

> However, if I follow the google directions here: https://developers.google.com/identity/gsi/web/guides/display-button#html_1
and add the html code:

Unfortunately, that JS-initiated flow is completely non-standard and cannot be used with the OpenIddict client, that requires handling the authentication flow from A to Z (from the generation of the authorization request with a `state` it controls to the validation of the authorization response).

I'd recommend using the authorization code flow, which is secure and standard. If having a "Login with Google" button is important for you, you can still use one that points to a local endpoint in your app that triggers an authentication challenge.

Hope it was clear 😃

**Comment by jacob925** [comment]
Hi @kevinchalet , 
Thanks for the quick response. I am definitely more of an application developer and have limited experience with authentication flows. 
I will continue on with the current support auth flow.

-Jacob

**Comment by kevinchalet** [comment]
> Thanks for the quick response.

My pleasure!

> I will continue on with the current support auth flow.

👍🏻
