### ISSUE TITLE
Three-party login exception

### ISSUE THREAD

**Issue by wangyuzhu** [openiddict/openiddict-samples#339]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

OpenIddict.AspNetCore 5.8.0

### Describe the bug

//Setting
builder.Services.AddOpenIddict(.....).AddClient(options =>{
options.UseWebProviders(s =>
{
    s.AddGitHub(o =>
    {
        o.SetClientId("Ov23liaOAoRdJmBZPLbz")
        .SetClientSecret("88378907a1c1e4885c5ce26a85d3cf5a1e8eba2b")
        .SetRedirectUri("callback/login/github");
    })
});
})

[HttpGet("~/callback/login/{provider}"), HttpPost("~/callback/login/{provider}"), IgnoreAntiforgeryToken]
public async Task<ActionResult> LogInCallback(string code, string state)
{
   var result = await HttpContext.AuthenticateAsync(OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);
throw error >>>>>grant type must be specified when triggering authentication demands from endpoints that are not managed by the OpenIddict client stack. This error may also indicate that the redirection endpoint was not correctly enabled in the OpenIddict client options
}

![err](https://github.com/user-attachments/assets/ab882d66-e922-4df4-bf4c-36d2e410a449)

### To reproduce

[HttpGet("~/callback/login/{provider}"), HttpPost("~/callback/login/{provider}"), IgnoreAntiforgeryToken]
public async Task<ActionResult> LogInCallback(string code, string state)
{
   var result = await HttpContext.AuthenticateAsync(OpenIddictClientAspNetCoreDefaults.AuthenticationScheme);
throw error >>>>>grant type must be specified when triggering authentication demands from endpoints that are not managed by the OpenIddict client stack. This error may also indicate that the redirection endpoint was not correctly enabled in the OpenIddict client options
}

### Exceptions (if any)

```shell
grant type must be specified when triggering authentication demands from endpoints that are not managed by the OpenIddict client stack. This error may also indicate that the redirection endpoint was not correctly enabled in the OpenIddict client options
```

**Comment by kevinchalet** [comment]
Hi,

Can you please share a repro?

**Comment by wangyuzhu** [comment]
repo:https://github.com/openiddict/openiddict-samples

![1726190675236](https://github.com/user-attachments/assets/0450e093-b807-4c15-9fca-626419385e05)
![eee](https://github.com/user-attachments/assets/0117968f-5c41-4e1c-8a94-7b189b943c03)

**Comment by wangyuzhu** [comment]
> Hi,
> 
> Can you please share a repro?

repo:https://github.com/openiddict/openiddict-samples


![eee](https://github.com/user-attachments/assets/0117968f-5c41-4e1c-8a94-7b189b943c03)

**Comment by kevinchalet** [comment]
I said repro - as in "minimal project that reproduces the issue and that I can debug locally", not repository 😃 
I just tested the Velusia sample and it worked just fine, so you likely tweaked it in a way that broke something. Without sharing a repro, I can't help you at all.
