### ISSUE TITLE
Access resource server from authorization server

### ISSUE THREAD

**Issue by jv19** [openiddict/openiddict-samples#35]
Hello. I have a scenario similar to the ImplicitFlow sample but with the additional need to call one of the resource servers from the authorization server. For example, once the user has signed in I need to have a page in the authorization server to view/edit the user's profile, and some of those details need to be pulled from a resource server. What would be the recommended way to approach this?

**Comment by PinpointTownes** [comment]
Hey,

To make them more visible for the community, questions should be posted on StackOverflow: https://stackoverflow.com/questions/tagged/openiddict.

See you there!
