### ISSUE TITLE
unsupported_grant_type, password flow

### ISSUE THREAD

**Issue by szykov** [openiddict/openiddict-samples#36]
I tried password flow sample and when I send xhr post request with grant_type=password I receive this error:

> {
>   "error": "unsupported_grant_type",
>   "error_description": "The specified grant_type is not supported by this authorization server."
> }

Same behavior in my local project.

**Comment by PinpointTownes** [comment]
I can't reproduce it.

If you believe it's a bug, please provide a minimal, complete, and verifiable example.

**Comment by szykov** [comment]
Well what I did:
1) Cloned repo
2) Set as startup project authorization server in password flow folder.
3) Sent post request using postman to that url: http://localhost:58795/connect/token

Header:

>  Content-Type - application/x-www-form-urlencoded

Body:

> grant_type - password 
> username - username
> password - password


Received the error above.

**Comment by PinpointTownes** [comment]
It's not really what I'd call a verifiable example... :trollface: 

Feel free to test the password flow console client sample to confirm it works as expected.

**Comment by szykov** [comment]
I verified why the error was.
Well, my grant_type was actually {password }. I left space at the end of the word. Unbelievable.
¯\_(ツ)_/¯

**Comment by PinpointTownes** [comment]
...
