### ISSUE TITLE
Does the id_token have any purpose in the password flow?

### ISSUE THREAD

**Issue by astegmaier** [openiddict/openiddict-samples#40]
The sample authorization controller in the Password Flow Authentication server has some code that causes the /connect/token endpoint issue an id_token as well as an authorization token:

https://github.com/openiddict/openiddict-samples/blob/master/samples/PasswordFlow/AuthorizationServer/Controllers/AuthorizationController.cs#L163-L170

Does the id_token serve any purpose in an app that only uses the password flow? It doesn't seem that the client is using the id_token for anything. Also, the [ROPC spec](https://tools.ietf.org/html/rfc6749#section-4.3) appears to be an OAuth concept that isn't mentioned in the OpenId Connect spec and doesn't mention an id_token.

Forgive me if this is obvious--I'm trying to use the samples as a learning tool to understand OpenIdConnect and OAuth, so I'm wondering if this is a sign of something I don't know about, or if it's just unnecessary code copied over from the other samples. If the latter, perhaps it should be remove from the samples?

**Comment by PinpointTownes** [comment]
> Does the id_token serve any purpose in an app that only uses the password flow?

No matter what's the exact flow you're using, the identity token is always a convenient way to flow user data/claims from the authorization server to the client application (e.g the username, the email address, the birthday, etc.).

> It doesn't seem that the client is using the id_token for anything.

That's right. The initial plan was to use it in the client app (to display the username) but I didn't take the time to add `id_token` decoding support.

> Also, the ROPC spec appears to be an OAuth concept that isn't mentioned in the OpenId Connect spec and doesn't mention an id_token.

True. ASOS (the OIDC server middleware) deliberately allows you to include the `id_token` in the token response by extending the original OAuth2 specification, just like what the "OAuth2 multiple response types" specification did with the interactive OAuth2 flows when the `id_token` concept was "backported" to OAuth2: https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html

> If the latter, perhaps it should be remove from the samples?

Returning an identity token doesn't harm, but if you don't like that, don't add the `openid` scope when calling `ticket.SetScopes(...)`.

**Comment by astegmaier** [comment]
Thanks for the response! That helps clarify things a lot. I think this is just part of the natural process of trying to learn from a sample, because you have to distinguish between the truly essential parts, and the parts that are optional conventions or suggestions.
