### ISSUE TITLE
Facebook authentication - ASP.NET Core.

### ISSUE THREAD

**Issue by Ciejaa** [openiddict/openiddict-samples#44]
Hi,

Is there any sample app with Facebook authentication using openiddict in asp.net core?

Thanks

**Comment by PinpointTownes** [comment]
Hey,

> Is there any sample app with Facebook authentication using openiddict in asp.net core?

No, but feel free to take a look at the code flow sample that uses the Google authentication middleware (all the social providers work exactly the same way).
