### ISSUE TITLE
Refresh token flow without identity

### ISSUE THREAD

**Issue by galiolas** [openiddict/openiddict-samples#51]
Hello, i've found a code on the internet to generate a token without using identity to retrieve the user.
I need to do the same hing for the refresh token. Here is the link http://kevinchalet.com/2017/01/30/implementing-simple-token-authentication-in-aspnet-core-with-openiddict/

I need to create the ticket without using coe like 'signInManager.CreateUserPrincipalAsync(user)'

Other queston : could you send me what I need to pass to the request for refreshing a token ? I don't manage to pass in the 'else if (request.IsRefreshTokenGrantType())' 

This is what I pass actually to the request : 

grant_type  :refresh_token
scope : openid offline_access
refresh_token: a token generated with the code in the link above.

This is the response :  
{
    "error": "invalid_grant",
    "error_description": "The specified refresh token is invalid."
}

This is a link to show you my code 
https://gist.github.com/galiolas/59597fa61128e27cd27b53cd9eddd8aa

I don't managed to pass in the 
'else if (request.IsRefreshTokenGrantType())'  with the request params I write above.

Thanks

**Comment by PinpointTownes** [comment]
Replied by mail.

**Comment by codemaveric** [comment]
Hii, I also have the same issue, can you post the solution here

**Comment by alespabtoptal** [comment]
Please post a solution here. Also the same issue.

**Comment by tchadwick** [comment]
@galiolas Can you respond with the solution @kevinchalet recommended?

**Comment by tchadwick** [comment]
Hey @codemaveric and @alespabtt I know this is old, but at looking at the source code, I found that you need to override the DeserializeRefreshToken method and make sure you set the context.Ticket property.

`public override async Task DeserializeRefreshToken(DeserializeRefreshTokenContext context)
        {
            context.Ticket = new AuthenticationTicket(new ClaimsPrincipal(), OpenIddictValidationDefaults.AuthenticationScheme);
            context.HandleDeserialization();
        }`
