### ISSUE TITLE
Invalid Object Name OpenIddictApplication when using ClientCredentialsFlow Sample

### ISSUE THREAD

**Issue by wmccullough** [openiddict/openiddict-samples#53]
Hello!

I am using the following sample in order to try and implement client credentials flow:

https://github.com/openiddict/openiddict-samples/tree/dev/samples/ClientCredentialsFlow/AuthorizationServer

I have followed this largely to the letter, only exception being that instead of ApplicationDbContext, I named my context AuthDbContext. When I attempt to run the application, I recieve the following error:

System.Data.SqlClient.SqlException: 'Invalid object name 'OpenIddictApplications'.'

I assumed that Openiddict would create the tables in the database for me. Am I misunderstanding something?

EDIT: I wanted to also add that I tested my connection string in a console app to ensure no hidden characters or mistakes, and I know for sure that it is valid.

**Comment by wmccullough** [comment]
I have solved this. I missed the note about how an existing database wouldn't be modified. I changed the initial catalog in my connection string to a non-existent database and it works perfectly. Thanks for this project, it's a life saver!

**Comment by PinpointTownes** [comment]
Glad you found the issue. Hope it will help other people seeing the same error.

**Comment by hajimenez** [comment]
> I have solved this. I missed the note about how an existing database wouldn't be modified. I changed the initial catalog in my connection string to a non-existent database and it works perfectly. Thanks for this project, it's a life saver!

Can I Have a connection string to a non-existent database sample for .net core?
