### ISSUE TITLE
Update the implicit flow demo to aurelia-open-id-connect 1.0.

### ISSUE THREAD

**Issue by shaunluttin** [openiddict/openiddict-samples#56]

**Comment by PinpointTownes** [comment]
Congrats for the release :clap:

**Comment by davidtimovski** [comment]
Any news on this one?

**Comment by shaunluttin** [comment]
There isn't much news on this one. I've been away from the aurelia-open-id-connect project for some time now, and it is not clear when time will permit coming back to it.

**Comment by shaunluttin** [comment]
Closed with https://github.com/openiddict/openiddict-samples/pull/65. 

@davidtimovski.
