### ISSUE TITLE
connect/token issue

### ISSUE THREAD

**Issue by BehnamAbdy** [openiddict/openiddict-samples#6]
hi
i cloned the samples and ran both  server and client projects,they work good and i make a user and login with it through mvc UI, but when i want to login with the same user through js  and i post my credentials to http://localhost:54540/connect/token expecting to get the token but always retruns 400 bad request with error of {"error": "unsupported_grant_type"
"error_description": "The specified grant_type parameter is not allowed."}

here is the credentails i post to server : username=username&password=pass123&grant_type=password
with contenttype :application/x-www-form-urlencoded

also i tried posting them as json with related contenttype but failed again

regards

**Comment by PinpointTownes** [comment]
You must call `AllowPasswordFlow()` to allow OpenIddict to serve `grant_type=password` requests.

**Comment by BehnamAbdy** [comment]
thanks a lot,
 i wonder it was not mentioned in the samples

**Comment by PinpointTownes** [comment]
The MVC sample only enables authorization code flow support. A sample dedicated to the resource owner password credentials is coming: https://github.com/openiddict/openiddict-samples/pull/2.

**Comment by PinpointTownes** [comment]
Closing. Feel free to reopen if you're still seeing an issue.

**Comment by piotrek-k** [comment]
Has something changed since then? I've sent a request as it is [described here](https://tools.ietf.org/html/rfc6749#section-4.3.2)
![postman](https://cloud.githubusercontent.com/assets/5506878/22083668/659190da-ddcd-11e6-93e3-494d7c073b29.png)

```csharp
        [HttpPost("~/api/connect/token"), Produces("application/json")]
        public async Task<IActionResult> Exchange(OpenIdConnectRequest request)
        {
            Debug.Assert(request.IsTokenRequest(),
                "The OpenIddict binder for ASP.NET Core MVC is not registered. " +
                "Make sure services.AddOpenIddict().AddMvcBinders() is correctly called.");

            if (request.IsAuthorizationCodeGrantType())
            {
                // Retrieve the claims principal stored in the authorization code.
                var info = await HttpContext.Authentication.GetAuthenticateInfoAsync(
                    OpenIdConnectServerDefaults.AuthenticationScheme);

                // Retrieve the user profile corresponding to the authorization code.
                var user = await _userManager.GetUserAsync(info.Principal);
                if (user == null)
                {
                    return BadRequest(new OpenIdConnectResponse
                    {
                        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                        ErrorDescription = "The authorization code is no longer valid."
                    });
                }

                // Ensure the user is still allowed to sign in.
                if (!await _signInManager.CanSignInAsync(user))
                {
                    return BadRequest(new OpenIdConnectResponse
                    {
                        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                        ErrorDescription = "The user is no longer allowed to sign in."
                    });
                }

                // Create a new authentication ticket, but reuse the properties stored
                // in the authorization code, including the scopes originally granted.
                var ticket = await CreateTicketAsync(request, user, info.Properties);

                return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
            }

            return BadRequest(new OpenIdConnectResponse
            {
                Error = OpenIdConnectConstants.Errors.UnsupportedGrantType,
                ErrorDescription = "The specified grant type is not supported."
            });
        }
```

`request.IsAuthorizationCodeGrantType()` equals false. I've also called `AllowPasswordFlow()` in `ConfigureServices` in `Startup.cs`.

**Comment by PinpointTownes** [comment]
Your token endpoint action doesn't include support for the password flow. Take a look at the samples in the samples repo.

**Comment by szykov** [comment]
@PinpointTownes 
could you please be more specific where else it should be added? In sample of @piotrek-k : 

> // Allow client applications to use the grant_type=password flow.
>                 .AllowPasswordFlow()

I did as in sample and as you wrote in your blog, but error still persists.

**Comment by PinpointTownes** [comment]
@szykov here: https://github.com/openiddict/openiddict-samples/blob/master/samples/PasswordFlow/AuthorizationServer/Startup.cs#L45

... and here: https://github.com/openiddict/openiddict-samples/blob/master/samples/PasswordFlow/AuthorizationServer/Controllers/AuthorizationController.cs#L35-L115

**Comment by szykov** [comment]
@PinpointTownes Sorry, I wasn't hoping for your fast answer and opened an issue: #36

The thing is that in sample project it also isn't working.
