### ISSUE TITLE
Potential bug in refresh-flow sample on client side

### ISSUE THREAD

**Issue by philippk80** [openiddict/openiddict-samples#62]
Hello,
on https://github.com/openiddict/openiddict-samples/blob/master/samples/RefreshFlow/AngularApp/src/core/auth.service.ts  is a bug in my opinion. 
Starting at line 108. There should be a map to return the Observable<AuthTokenModel>. 
Or other functions have to be changed.
I couldn't compile this.

I think the right implementation is:

```
private getTokens(data: RefreshGrantModel | LoginModel, grantType: string): Observable<AuthTokenModel> {
    const headers = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' });
    const options = new RequestOptions({ headers: headers });

    Object.assign(data, { grant_type: grantType, scope: 'openid offline_access' });

    const params = new URLSearchParams();
    Object.keys(data)
      .forEach(key => params.append(key, data[key]));
    return this.http.post(`${environment.baseApiUrl}/connect/token`, params.toString(), options)
      .pipe(
        map(res => res.json()),
        tap(res => {
          const tokens: AuthTokenModel = res;
          const now = new Date();
          tokens.expiration_date = new Date(now.getTime() + tokens.expires_in * 1000).getTime().toString();

          const profile: ProfileModel = jwtDecode(tokens.id_token);

          this.storeToken(tokens);
          this.updateState({ authReady: true, tokens, profile });
      }));
  }
```

**Comment by philippk80** [comment]
and here https://github.com/openiddict/openiddict-samples/blob/dev/samples/RefreshFlow/AngularApp/src/app/register/register.component.ts
is a ; too much after the onSubmit() function

**Comment by georgeonofrei** [comment]
I've not written the sample, but i agree this looks like a bug. I would avoid the "do" as if you have multiple subscriptions to the Observable, do would be executed a lot of times.
