### ISSUE TITLE
Using OpenIddict with JWT Bearer Authentication with a .NET Framework 4.6 Resource server

### ISSUE THREAD

**Issue by daveyjay** [openiddict/openiddict-samples#63]
I am using OpenIddict with the implicit flow for my .NET Core 2.1 combined API and Authorization server that uses JWT Bearer authentication and everything is working great.  

Now I need to add a second resource server which is a separate .NET 4.6.1 Framework web application using Web API 1.  (This is a reporting API which has to rely on the full .NET Framework).  Now I want to secure my Controller endpoint with the [Authorize] tag and get this to play nicely with my main Authorization Server endpoint using JWT Bearer access tokens.

I've seen different ways of setting up JWT Bearer authentication to secure the controller in Web API 1 projects- from writing a custom [JWTAuthentication] attribute filter, to using Owin middleware.  

Do you have an example or suggestion on the recommended way to configure a .NET Framework 4.x Resource server which uses the original WEB API (not version 2) with JWT Bearer authentication and allowing it to talk to the main OpenIddict .NET Core Authorization Server?  The existing samples that show Resource Servers are all in .NET Core.

**Comment by PinpointTownes** [comment]
Web API 1 is not compatible with OWIN so the middleware option is likely not going to be possible. If you can't migrate to Web API 2, a custom action filter is probably your best option.

FWIW, Web API 1 is considered obsolete for a long time now. Officially, it's still supported by MSFT but it hasn't been updated for ages. If you can, Web API 2 would be a wise decision.

(fun fact: Web API 1 was released in 2012, 3 years before the JWT specification was adopted :sweat_smile:)

**Comment by daveyjay** [comment]
Thanks for that info! Yes I agree this is pretty crazy having a product using WEB API 1 these days...I have updated everything to WEB API 2 but am still not able to get everything to work correctly.  

Do you have a sample of how to use a Resource Server with WEB API2 and Owin?

A bit of background....the third party library I was using ( a REST Reporting API) has been frustrating - their support mentioned that their product used WEB API 1, however their VS wizard that creates their reporting server endpoint sets up the project in .NET Framework 4.6, yet in the web.config it targets 4.0.  I have had a real mess getting all the libraries sorted out.

I have it now running on .NET Framework 4.5 and everything besides the JWT Authorization part is working.  I've got the Microsoft.Owin.Security.Jwt package installed.  The OpenIddict samples Resource Server projects are using .NET Core and I notice that in the Startup.cs files the JWT Bearer part is set up in the ConfigureServices method, and the syntax looks different than the examples I have seen.  I have also seen quite a variety of different ways to set up the app.UseJwtBearerAuthentication code - nothing has worked for me yet. 

Here is the code that I have in my ResourceServer Startup.cs

```

public void Configuration(IAppBuilder app)
{            
            //Not sure if I need this code here - it shows up in the .NET Core version under ConfigureServices
             // If you prefer using JWT, don't forget to disable the automatic
            // JWT -> WS-Federation claims mapping used by the JWT middleware:
            //
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

           app.UseJwtBearerAuthentication(
                new JwtBearerAuthenticationOptions
                {
                    AuthenticationMode = AuthenticationMode.Active,
                    AllowedAudiences = new[] { "reporting-api" }, 
                    TokenValidationParameters = new TokenValidationParameters
                    {
                        AuthenticationType = "Bearer",
                        ValidIssuer = "http://localhost:50909/",
                        ValidAudience = "reporting-api",
                        NameClaimType = "sub",
                        RoleClaimType = System.Security.Claims.ClaimTypes.Role
                    }
                });
}
```

Is there a piece I am missing?

**Comment by PinpointTownes** [comment]
> Do you have a sample of how to use a Resource Server with WEB API2 and Owin?

Not for JWT. The aspnet-contrib validation handler has an OWIN version but it only works with the default token format (opaque).

> Is there a piece I am missing?

You must also register the issuer signing key. Unlike the ASP.NET Core middleware, the OWIN JWT middleware doesn't do OIDC discovery.

**Comment by daveyjay** [comment]
> Do you have a sample of how to use a Resource Server with WEB API2 and Owin?

>_Not for JWT. The aspnet-contrib validation handler has an OWIN version but it only works with the default token format_

> Is there a piece I am missing?
>_You must also register the issuer signing key. Unlike the ASP.NET Core middleware, the OWIN JWT middleware doesn't do OIDC discovery._

Sorry I am a little unclear on what I need to do.....does this mean that I will not be able to get my .NET Framework 4.x Resource server using Owin to talk to OpenIddict using JWT? In other words I would have to switch back to the AddOAuthValidation authentication option and that is my only choice?  If I register the issuer signing key as you mention I need to do - will it still not work if the format is JWT?  

As far as registering the issuer signing key - this is something I have not configured yet - currently I am using the option .UseEphemeralSigningKey  (just trying to get everything working in development right now.)  I am not super familiar with working with certificates and signing keys etc and am finding the configuration of all of this to be a bit confusing - especially with JWT -  I guess there is no way to share the generated ephemeral key or use it in my resource server? 

And this may be a dumb question (but I am finding myself getting confused by all of the various options)  - if I am stuck with a .NET Framework 4.x API and I have to get this to work with JWT - in your opinion would it make sense to just bypass the OpenIddict authorization server entirely (since as you say the OWIN JWT middleware doesn't do OIDC discovery) and manually extract the sub claim from the access token using a custom filter on my resource server API endpoint (the sub claim is my user id) and validate it by talking to my database to fetch the user and whatever permissions they have?  

Appreciate any suggestions - been working on this for a few days and am going a bit stir crazy trying to figure out all the moving pieces ;-)

**Comment by daveyjay** [comment]
Update: I have played around with the ImplicitFlow sample and now have the sample converted over to using JWT Authentication and the main AuthorizationServer piece working with a certificate stored locally.  However, my .NET 4.x api endpoint still will not validate my JWT token.

Here are the steps I have taken:

1) I have created a self-signed certificate as mentioned in the sample Startup.cs file, using the Pluralsight utility.  That utility creates a thumbprint and is stored in the local machine store which I use as my key. (Prior to this I also attempted to use a certificate .pfx file as shown also in the sample commented out code, as well as trying the certificate  embedded in the assembly but was unable to get this to work - perhaps there is another step not shown in the sample?)

```
In the ConfigureServices method....

// Register the OpenIddict services.
            services.AddOpenIddict(options =>
            {
                // Register the Entity Framework stores.
                options.AddEntityFrameworkCoreStores<ApplicationDbContext>();

                // Register the ASP.NET Core MVC binder used by OpenIddict.
                // Note: if you don't call this method, you won't be able to
                // bind OpenIdConnectRequest or OpenIdConnectResponse parameters.
                options.AddMvcBinders();

                // Enable the authorization, logout, userinfo, and introspection endpoints.
                options.EnableAuthorizationEndpoint("/connect/authorize")
                       .EnableLogoutEndpoint("/connect/logout")
                       .EnableIntrospectionEndpoint("/connect/introspect")
                       .EnableUserinfoEndpoint("/api/userinfo");

                // Mark the "email", "profile" and "roles" scopes as supported scopes.
                options.RegisterScopes(OpenIdConnectConstants.Scopes.Email,
                                       OpenIdConnectConstants.Scopes.Profile,
                                       OpenIddictConstants.Scopes.Roles);

                // Enable scope validation, so that authorization and token requests
                // that specify unregistered scopes are automatically rejected.
                options.EnableScopeValidation();

                // Note: the sample only uses the implicit code flow but you can enable
                // the other flows if you need to support implicit, password or client credentials.
                options.AllowImplicitFlow();

                // During development, you can disable the HTTPS requirement.
                options.DisableHttpsRequirement();

                // Register a new ephemeral key, that is discarded when the application
                // shuts down. Tokens signed using this key are automatically invalidated.
                // This method should only be used during development.
                //options.AddEphemeralSigningKey(); // Comment out the ephemeral signing key!

                options.AddSigningCertificate("051F9775007856E9943978E86B30955A9AA4911A"); // this GUID is the same as the "thumbprint" generated by the Pluralsight self-signing utility               //
                // Note: to use JWT access tokens instead of the default
                // encrypted format, the following line is required:
                //
                options.UseJsonWebTokens();
            });

           
            //Disable the automatic JWT->WS - Federation claims mapping used by the JWT middleware
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.Authority = "http://localhost:12345/";
                    options.MetadataAddress = "http://localhost:12345/";
                    //options.Audience = "ResourceServer1";
                    options.RequireHttpsMetadata = false;

                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = OpenIdConnectConstants.Claims.Subject,
                        RoleClaimType = OpenIdConnectConstants.Claims.Role,
                        ValidateIssuer = true,
                        ValidateIssuerSigningKey = true,
                        ValidAudiences = new List<string>
                        {
                            "resource-server-1",  
                           "resource-server-2"
                            "resource-server-3" // new .NET Framework 4 WEB API 2 app added
                        },
                        //IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("051F9775007856E9943978E86B30955A9AA4911A")) // can still login with or without this key
                    };
                }); 

```

 In my new .NET WEB Api Project (resource-server-3) I have the following code in Startup.cs

```
app.UseJwtBearerAuthentication(
                new JwtBearerAuthenticationOptions
                {

                    AuthenticationMode = AuthenticationMode.Active,
                    
                    AllowedAudiences = new[] { "resource-server-3" },
                    
                    TokenValidationParameters = new TokenValidationParameters
                    {
                        AuthenticationType = "Bearer",
                        ValidIssuer = "http://localhost:12345/",
                        ValidAudience = "resource-server-3",
                        NameClaimType = "sub",
                        RoleClaimType = System.Security.Claims.ClaimTypes.Role,
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("051F9775007856E9943978E86B30955A9AA4911A"))
                       

                    },
                     
                });
```

As you can see I've added the signing key - but am still getting the Unauthorized 401 when trying to hit this endpoint...

**Comment by daveyjay** [comment]
Update: I have everything working!

I will post my solution here in case it helps anyone out.  

Again, the original problem is how to get JWT bearer authentication working with a .NET Framework 4.x Resource server so that the API endpoint can be locked down with the [Authorize] attribute and the token validated.

The part that I was getting confused with was configuring OpenIddict is the difference between when you have to use certificates, signing keys, secrets, etc.  Lots of terminology to get this wired up and in the samples, I did not see any code to do with signing keys.

So to get this to work, I did not need to change anything with the certificates - I can actually leave the ephemeral signing keys for now.

This is all based on the code for Implicit flow in the samples.  I added a .NET Framework Web Application with WEB API, and installed the following packages

Microsoft.AspNet.Authentication.Jwt
System.IdentityModel.Tokens.Jwt
Microsoft.Owin.Host.SystemWeb  (to get Startup.cs to work)


```
             // Register the OpenIddict services.
            services.AddOpenIddict(options =>
            {
                // Register the Entity Framework stores.
                options.AddEntityFrameworkCoreStores<ApplicationDbContext>();

                // Register the ASP.NET Core MVC binder used by OpenIddict.
                // Note: if you don't call this method, you won't be able to
                // bind OpenIdConnectRequest or OpenIdConnectResponse parameters.
                options.AddMvcBinders();

                // Enable the authorization, logout, userinfo, and introspection endpoints.
                options.EnableAuthorizationEndpoint("/connect/authorize")
                       .EnableLogoutEndpoint("/connect/logout")
                       .EnableIntrospectionEndpoint("/connect/introspect")
                       .EnableUserinfoEndpoint("/api/userinfo");

                // Mark the "email", "profile" and "roles" scopes as supported scopes.
                options.RegisterScopes(OpenIdConnectConstants.Scopes.Email,
                                       OpenIdConnectConstants.Scopes.Profile,
                                       OpenIddictConstants.Scopes.Roles);

                // Enable scope validation, so that authorization and token requests
                // that specify unregistered scopes are automatically rejected.
                options.EnableScopeValidation();

                // Note: the sample only uses the implicit code flow but you can enable
                // the other flows if you need to support implicit, password or client credentials.
                options.AllowImplicitFlow();

                // During development, you can disable the HTTPS requirement.
                options.DisableHttpsRequirement();

                // Register a new ephemeral key, that is discarded when the application
                // shuts down. Tokens signed using this key are automatically invalidated.
                // This method should only be used during development.
                options.AddEphemeralSigningKey();  // can leave this for now and not worry about certificates

                options.AddSigningKey(new SymmetricSecurityKey(Encoding.UTF8.GetBytes("953183eb-988d-403e-8b8a-7dd9cd44e303"))); // using a new GUID for client secret

                // Note: to use JWT access tokens instead of the default
                // encrypted format, the following line is required:
                //
                options.UseJsonWebTokens();


            });
          
             // Configure JWT Bearer Authentication
            //Disable the automatic JWT->WS - Federation claims mapping used by the JWT middleware
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.Authority = "http://localhost:12345/";  
                    options.MetadataAddress = "http://localhost:12345/";
                    options.RequireHttpsMetadata = false;

                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = OpenIdConnectConstants.Claims.Subject,
                        RoleClaimType = OpenIdConnectConstants.Claims.Role,
                        ValidateIssuer = true,
                        ValidateIssuerSigningKey = true,
                        ValidAudiences = new List<string>
                        {
                            "resource-server-1",  
                            "resource-server-2",
                            "resource-server-3"  // this is the new .NET Framework 4.6 WEB API Owin project
                        },

                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("953183eb-988d-403e-8b8a-7dd9cd44e303")) // using same GUID secret as above                    };
                }); 

```

I added some code to seed the OpenIddict tables with the new resource server...

```

private async Task InitializeAsync(IServiceProvider services)
        {

     .......

   async Task CreateApplicationsAsync()
                {
                    ....

                 if (await manager.FindByClientIdAsync("resource-server-3") == null)
                    {
                        var descriptor = new OpenIddictApplicationDescriptor
                        {
                            ClientId = "resource-server-3",
                            ClientSecret = "b2efc782-d0fe-466a-9bc3-100db7f8f9ba",
                            Permissions =
                            {
                                OpenIddictConstants.Permissions.Endpoints.Introspection
                            }
                        };

                        await manager.CreateAsync(descriptor);
                    }
                }


            async Task CreateScopesAsync()
                {    

                     ....

                   if (await manager.FindByNameAsync("api3") == null)
                    {
                        var descriptor = new OpenIddictScopeDescriptor
                        {
                            Name = "api3",
                            Resources = { "resource-server-3" }
                        };

                        await manager.CreateAsync(descriptor);
                    }

```

Now in the new ResourceServer3 endpoint project,  in Startup.cs - here is the configuration
```

public void Configuration(IAppBuilder app)
        {
              
            // If you prefer using JWT, don't forget to disable the automatic
            // JWT -> WS-Federation claims mapping used by the JWT middleware:
            //
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

            app.UseJwtBearerAuthentication(

                new JwtBearerAuthenticationOptions
                {

                    AuthenticationMode = AuthenticationMode.Active,

                    AllowedAudiences = new[] { "resource-server-3" },
                    TokenValidationParameters = new TokenValidationParameters
                    {
                        AuthenticationType = "Bearer",
                        ValidIssuer = "http://localhost:12345/",
                        ValidAudience = "resource-server-3",
                        NameClaimType = "sub",
                        RoleClaimType = System.Security.Claims.ClaimTypes.Role,                        ValidateIssuerSigningKey = true,
                        IssuerSigningKey =
                            new SymmetricSecurityKey(Encoding.UTF8.GetBytes("953183eb-988d-403e-8b8a-7dd9cd44e303")) // GUID secret                       
 
                    },
         });

```

Here is the secured endpoint for resource-server-3

```

using System.Security.Claims;
using System.Web.Http;
using System.Web.Http.Cors;

namespace ResourceServer03.Controllers.api
{
    public class PrivateController : ApiController
    {
        [EnableCors(origins: "*", headers: "*", methods: "*")] // origins: "http://localhost:9000"
        [Authorize]
        [HttpGet]
        public IHttpActionResult Get()
        {
            var identity = User.Identity as ClaimsIdentity;
            if (identity == null)
            {
                return BadRequest();
            }

            return Ok($"You have authorized access to resources belonging to {identity.Name} on ResourceServer03.");
        }

    }
}
```


Everything works now - I can post to the secured private resource server endpoint and the JWT is validated successfully :-)

I have one outstanding question though (which probably shows that I don't fully understand all the moving parts...)  - what is the significance of the client secret when setting up the OpenIddict application?  The signing key that I've used is a completely different secret and everything seems to work ok.  Is the client secret that gets populated into the database still used when you create your own signed key?

**Comment by rubit0** [comment]
I was having some troubles getting JWT validation to run because in some of the examples the comment regarding this setting is about the audience:

`options.Audience = "resource-server"; //This must be included in ticket creation`

And I added this audience into the ticket but it that didn't worked, at least in my case.
What I had to do is instead to add it as a resource, not an audience, like this:

```
Inside the AuthorizationController:

CreateTicketAsync(...)
{
    ...
    ticket.SetResources("resource-server");   
    ...
}
```

Now the JWT stack works, I hope this comment might be helpful to some who found this via a google search.

**Comment by justinteaw** [comment]
I am trying a similar example with .net framework but couldn't get it work....
