### ISSUE TITLE
JSON serialization namining convention for ResponseMessage with ASP.NET Core 3.1

### ISSUE THREAD

**Issue by mastersign** [openiddict/openiddict-samples#81]
* Version: OpenIddict 2.0.1
* Framework: ASP.NET Core 3.1
* Example: Password Flow

When sending the `SignInResult` with `Controller.SignIn()` the JSON formatted response uses camel case naming instead of snake case. E.g. `access_token` reaches the client as `accessToken`.

What could be the cause?

**Comment by kevinchalet** [comment]
No idea (it's certainly not expected). Do you have a public repro somewhere?

**Comment by mastersign** [comment]
Never mind, it was an error in the logging code of my client. Sorry to have wasted your time.
