### ISSUE TITLE
Determine why the JS samples no longer compile

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-samples#86]
The `Imynusoph.Client` (Aurelia) and `Zirku.Client` (Angular) no longer compile correctly. We should determine what's the root cause and fix it. If it's not easy to fix, we'll need to remove these samples.

**Comment by mrukas** [comment]
I tried to run the Zirku.Client and also ran into issues.
I got it working with the newest Node.js the following way:

- Delete package-lock.json
- Upgrade webpack and webpack-cli to the newest versions
- npm install
- npm start

I used npm because i didn't have yarn installed.

**Comment by kevinchalet** [comment]
Looks like everything is now working properly (the issue you were seeing was likely a same-site problem, fixed when moving to SSL/TLS).
