### ISSUE TITLE
Add a device flow sample

### ISSUE THREAD

**Issue by kevinchalet** [openiddict/openiddict-samples#88]
The code could be easily copied from the MVC engineering sample in the main repository: https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Controllers/AuthorizationController.cs

**Comment by mohamed-seada-1994** [comment]
I would like to work on this sample

**Comment by kevinchalet** [comment]
Great, thanks. It's all yours! 😄

**Comment by mohamed-seada-1994** [comment]
Here are some details about the sample, I want to check with you before making the PR
1. The client is MVC web app represnting the flow of user authorization to access his gaming library in a gaming console.
2. The client will use the device grant to get the tokens first time, after that it will use refresh grant to get fresh tokens.
3. The client will use sessions to store `device_code` and `refresh_token`
4. `access_token` and `id_token` will be stored in cookies using `CookieAuthenticationDefaults.AuthenticationScheme`
5. The server will not support the authentication endpoint as it's not required for the device grant

**Comment by jhancock4d** [comment]
@mohamed-seada-1994 Any word on this? I can't find any instructions on device flow to implement on the server side so I'm very interested in what you've got. Happy to help if you've got something to start from.

**Comment by mohamed-seada-1994** [comment]
The server implementation is completed, It's the same implementation in the sample in the first link, i got busy recently, the remaining is some of the client side implementation of the sample
I will make a branch with the current state, you could see it for now

**Comment by mohamed-seada-1994** [comment]
@jhancock4d 
https://github.com/mohamed-seada-1994/openiddict-samples/tree/Device-flow-sample-incompleted

**Comment by mohamed-seada-1994** [comment]
@kevinchalet , @jhancock4d  
Please check this PR with console client #151

**Comment by jhancock4d** [comment]
@mohamed-seada-1994 Looks good!

@kevinchalet  In general with the samples all of the service workers aren't passing the cancellationToken where they should be.

**Comment by kevinchalet** [comment]
> @kevinchalet In general with the samples all of the service workers aren't passing the cancellationToken where they should be.

Semantically, I'm not convinced the "host is shutting down" signal should be used to abort database initialization, which is typically not code you want to stop before things are fully set up. It's the reason why none of the samples passes the cancellation token.

**Comment by jhancock4d** [comment]
@kevinchalet I'd argue that EF Core if it gets cancellation token and is cancelled will rollback the transaction and thus reverse the migration that is running which is important if it is closing because you could end up in an unstable state.

**Comment by kevinchalet** [comment]
> is cancelled will rollback the transaction and thus reverse the migration that is running which is important if it is closing because you could end up in an unstable state

It's not always possible (e.g MySQL: https://dev.mysql.com/doc/refman/8.0/en/cannot-roll-back.html)

Anyway, if you prefer using cancellation tokens in the .NET workers, nothing prevents you from doing that in your own code 😃 

(and FWIW, until 6.0, EF Core didn't even support running migrations in user-defined transactions)
