### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by zh-wowtv** [openiddict/openiddict-samples#9]
I got the following error message when I run `dotnet run`:

> Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.
>    at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
>    at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)

I know MS Sql Server is only running in windows. But I'd like to run my web app in Linux (currently testing under Mac OSX) and connect to MSSql Server in Windows. Is this possible? Thanks.

**Comment by PinpointTownes** [comment]
It's really something you should ask to the EntityFramework team, but I guess it's simply caused by the fact the sample uses integrated security (= "Windows Authentication"). Change that and it should work.

**Comment by zh-wowtv** [comment]
@PinpointTownes Can you give me a little more hints? Where to change the integrated security and what should I change it to? Thanks.

**Comment by PinpointTownes** [comment]
Unfortunately, no, I can't (because I've never used SQL on Linux).

**Comment by zh-wowtv** [comment]
I think there must be a way to do so. Otherwise what's the point to support cross platform? Thanks anyway.

**Comment by devilsuraj** [comment]
@zh-wowtv you can use sql lite on linux , If you are using yo generator you can get it in generated project or check this https://damienbod.com/2015/08/30/asp-net-5-with-sqlite-and-entity-framework-7/

**Comment by zh-wowtv** [comment]
@devilsuraj Thanks. I'll go through it. But I heard Entity-framework core doesn't support Store Procedure yet. Is that true?

**Comment by jayrulez** [comment]
@zh-wowtv Postgresql is also pretty well supported at this point.

**Comment by zh-wowtv** [comment]
@jayrulez But my existing database is MSSql Server. I only want to change my web service to REST API and I want to run my REST API in linux.

Thanks anyway.

**Comment by ilmax** [comment]
@zh-wowtw please consider using a password based connection string on Linux. Win auth is not supported ATM.

**Comment by devilsuraj** [comment]
@zh-wowtv yes it doesnt https://github.com/aspnet/EntityFramework/issues/245 , also check this answer http://stackoverflow.com/questions/28599404/how-to-run-stored-procedures-in-entity-framework-7

**Comment by zh-wowtv** [comment]
@devilsuraj A bit confusing at this topic. Is EF 6.x only supported in Windows platform and it supports store procedure, am I right? What I'm planing to do is to write an application which can be running in any platform. If this is the case, I probably have to use EF 6.x first and migrate to EF Core later.

**Comment by PinpointTownes** [comment]
> Is EF 6.x able to work with .net core at the same time?

No. It will only work on .NET Desktop.
