### ISSUE TITLE
Basic authentication in front of openiddict authorization

### ISSUE THREAD

**Issue by serkanz** [openiddict/openiddict-samples#94]
Is it possible to use basic authentication and openiddict together? Any sample code would make sense.

Thanks

**Comment by kevinchalet** [comment]
I'm not sure I understand what you mean exactly by "Basic authentication in front of openiddict authorization". Care to elaborate?

**Comment by serkanz** [comment]
> I'm not sure I understand what you mean exactly by "Basic authentication in front of openiddict authorization". Care to elaborate?

I'm sorry , writing from GitHub mobile app. Concerning authorization code flow, What I mean is my client will make request to authorization server with "Authorization: Basic xyzabc" header. So I want to authenticate it automatically.

**Comment by kevinchalet** [comment]
Assuming you're referring to the `client_secret_basic` client authentication method, then yes, it's fully supported by the token, introspection, revocation and device endpoints.

If you're looking for a way to construct the `Basic` authentication header, you can take a look at https://github.com/openiddict/openiddict-core/blob/beb6b3e92bf1dc5bdd7204001d132d309e1d3c48/src/OpenIddict.Validation.SystemNetHttp/OpenIddictValidationSystemNetHttpHandlers.Introspection.cs#L72-L107

**Comment by serkanz** [comment]
> Assuming you're referring to the `client_secret_basic` client authentication method, then yes, it's fully supported by the token, introspection, revocation and device endpoints.
> 
> If you're looking for a way to construct the `Basic` authentication header, you can take a look at https://github.com/openiddict/openiddict-core/blob/beb6b3e92bf1dc5bdd7204001d132d309e1d3c48/src/OpenIddict.Validation.SystemNetHttp/OpenIddictValidationSystemNetHttpHandlers.Introspection.cs#L72-L107

Actually I'm talking about **Velusia** (Authorization Code flow) sample. I want to **locate my Authorization Server behind a Reverse Proxy**, which already authenticates users and proxies the request to auth server (with Http header **Authorization : Basic ##TOKEN##**). Thus, any request coming to my auth server is already authenticated. I want to use this authentication info and process further with authorization. 

So when I request ~/connect/authorize : 

https://github.com/openiddict/openiddict-samples/blob/606082375663e2a923e3d66a532b01f98736e30b/samples/Velusia/Velusia.Server/Controllers/AuthorizationController.cs#L62

**result.Succeeded** should be true. However that's not the case now.

**Comment by kevinchalet** [comment]
Oh, in this case, you're looking for basic-based user authentication, not client authentication.

Given that OpenIddict doesn't deal with user authentication, it's something you'll be able to implement without changing anything in the OpenIddict options.

You'll probably want to use https://github.com/blowdart/idunno.Authentication/tree/dev/src/idunno.Authentication.Basic to handle the basic authentication dance at the ASP.NET Core authentication layer.

**Comment by serkanz** [comment]
> Oh, in this case, you're looking for basic-based user authentication, not client authentication.
> 
> Given that OpenIddict doesn't deal with user authentication, it's something you'll be able to implement without changing anything in the OpenIddict options.
> 
> You'll probably want to use https://github.com/blowdart/idunno.Authentication/tree/dev/src/idunno.Authentication.Basic to handle the basic authentication dance at the ASP.NET Core authentication layer.

Thanks, that makes sense.
